
CREATE DATABASE juego;
USE juego;


CREATE TABLE `palabras` (
  `Id` int(11) NOT NULL,
  `Contenido` varchar(50) NOT NULL,
  `Tema` varchar(50) NOT NULL DEFAULT 'Sin Tema',
  `Pista` varchar(50) NOT NULL DEFAULT 'Sin Pista'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `partida` (
  `Id` int(11) NOT NULL,
  `Jugadores` varchar(20) NOT NULL DEFAULT 'Sin Nombre',
  `Score` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `rondas` (
  `Id` int(11) NOT NULL,
  `IdPalabra` int(11) NOT NULL,
  `IdPartida` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `palabras`
  ADD PRIMARY KEY (`Id`);

ALTER TABLE `partida`
  ADD PRIMARY KEY (`Id`);

ALTER TABLE `rondas`
  ADD PRIMARY KEY (`Id`),
  ADD KEY `IdPalabra` (`IdPalabra`),
  ADD KEY `IdPartida` (`IdPartida`);

ALTER TABLE `palabras`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `partida`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `rondas`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `rondas`
  ADD CONSTRAINT `rondas_ibfk_1` FOREIGN KEY (`IdPalabra`) REFERENCES `palabras` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `rondas_ibfk_2` FOREIGN KEY (`IdPartida`) REFERENCES `partida` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;


INSERT INTO PALABRAS VALUES(1,"ABECEDARIO","LIBRO","LISTA DE SIGNIFICADOS");
INSERT INTO PALABRAS VALUES(2,"BOLILLO","COMIDA","PAN");
INSERT INTO PALABRAS VALUES(3,"AGUACATE","FRUTA","TIEME UNA SEMILLA GRANDE");
INSERT INTO PALABRAS VALUES(4,"FERRETERIA","LUGAR","VENDE HERRAMIENTAS");
INSERT INTO PALABRAS VALUES(5,"ALCOHOL","SUSTANCIA","TRANSPARENTE");
INSERT INTO PALABRAS VALUES(6,"ZAPATOS","PRENDA","HAY DE MUCHOS MATERIALES");
INSERT INTO PALABRAS VALUES(7,"CALCETINES","PRENDA","NO SON TAN VISIBLES");
INSERT INTO PALABRAS VALUES(8,"AUTOMOVIL","PELICULA","PARA TRANSPORTARSE");
INSERT INTO PALABRAS VALUES(9,"INTELIGENCIA","CIENCIA","NO TODOS LA TIENEN");
INSERT INTO PALABRAS VALUES(10,"DETERGENTE","OBJETO","PARA LAVAR");
INSERT INTO PALABRAS VALUES(11,"PANDAS","ANIMAL","CARNIVORO QUE COME HOJAS");
INSERT INTO PALABRAS VALUES(12,"COMPUTADORA","OBJETO","AUTOMATIZAR TAREAS");
INSERT INTO PALABRAS VALUES(13,"USB","OBJETO","VOLATIL");
INSERT INTO PALABRAS VALUES(14,"CUMULONIMBUS","FENOMENOS NATURALES","TIPO DE NUBE");
INSERT INTO PALABRAS VALUES(15,"DEPARTAMENTO","LUGAR","PARA VIVIR");
INSERT INTO PALABRAS VALUES(16,"LAPIZ","OBJETO","UTILIZADO POR ALUMNOS");
INSERT INTO PALABRAS VALUES(17,"CANASTA","OBJETO","PARA LLEVAR COSAS");
INSERT INTO PALABRAS VALUES(18,"FELICIDAD","EMOCION","TIENE CABELLO AZUL");
INSERT INTO PALABRAS VALUES(19,"BICICLETA","TRANSPORTE","DOS FRENOS");
INSERT INTO PALABRAS VALUES(20,"EXMAQUINA","PELICULA","IA SE REVELA");
INSERT INTO PALABRAS VALUES(21,"ARMAGEDDON","PELICULA","ASTEROIDE");
INSERT INTO PALABRAS VALUES(22,"INSIDIOUS","PELICULA","POSEIDO POR UN DEMONIO");
INSERT INTO PALABRAS VALUES(23,"TERMINATOR","PELICULA","I WILL BE BACK");
INSERT INTO PALABRAS VALUES(24,"SPIDERMAN","PELICULA","UTILIZA LANZADORES");
INSERT INTO PALABRAS VALUES(25,"JUMANJI","PELICULA","JUEGO DE MESA");
INSERT INTO PALABRAS VALUES(26,"SHARKNADO","PELICULA","TIBURONES");
INSERT INTO PALABRAS VALUES(27,"SEÑALES","PELICULA","INVASION ALIEN");
INSERT INTO PALABRAS VALUES(28,"CLOVERFIELD","PELICULA","MOUNSTRUO GIGANTE");
INSERT INTO PALABRAS VALUES(29,"INTERESTELAR","PELICULA","ENCONTRAR UN NUEVO PLANETA");
INSERT INTO PALABRAS VALUES(30,"ZATHURA","PELICULA","JUMNAJI DEL ESPACIO");
INSERT INTO PALABRAS VALUES(31,"MATRAZ","OBJETO","FRASCO GRADUADO");
INSERT INTO PALABRAS VALUES(32,"ELEVADOR","OBJETO","PARA SUBIR");
INSERT INTO PALABRAS VALUES(33,"FOTOGRAFIA","OBJETO","IMAGEN DEL PASADO");
INSERT INTO PALABRAS VALUES(34,"ENCHILADAS","COMIDA","TORTILLA CON SALSA");
INSERT INTO PALABRAS VALUES(35,"WAFFLES","COMIDA","TIENE PATRON CUADRADO");
INSERT INTO PALABRAS VALUES(36,"HAMBURGUESAS","COMIDA","COMIDA DE GORDO");
INSERT INTO PALABRAS VALUES(37,"ESQUITES","COMIDA","EN BASO");
INSERT INTO PALABRAS VALUES(38,"PIZZA","COMIDA","PAN CON SALSA");
INSERT INTO PALABRAS VALUES(39,"EMPANADAS","COMIDA","2 DE CHOCLO 5 DE CARNE");
INSERT INTO PALABRAS VALUES(40,"ALBONDIGAS","COMIDA","EN FORMA DE BOLA");
INSERT INTO PALABRAS VALUES(41,"ESTOFADO","COMIDA","A FUEGO LENTO");
INSERT INTO PALABRAS VALUES(42,"TECLADO","OBJETO","PUEDES ESCRIBIR");
INSERT INTO PALABRAS VALUES(43,"TACOS","COMIDA","CON TORTILLA");
INSERT INTO PALABRAS VALUES(44,"DINOSAURIO","ANIMAL","TIENE BRAZOS CORTOS");
INSERT INTO PALABRAS VALUES(45,"FUTBOL","DEPORTE","PELOTA");
INSERT INTO PALABRAS VALUES(46,"BASQUETBOL","DEPORTE","CANCHA TECHADA");
INSERT INTO PALABRAS VALUES(47,"LOL","DEPORTE","GG NO TEAM");
INSERT INTO PALABRAS VALUES(48,"BADMINTON","DEPORTE","RAQUETA Y POLLITO");
INSERT INTO PALABRAS VALUES(49,"AJEDREZ","DEPORTE","ES DIVERTIDO");
INSERT INTO PALABRAS VALUES(50,"KENDO","DEPORTE","SPADAS DE BAMBU");
INSERT INTO PALABRAS VALUES(51,"KARATE","DEPORTE","CINTAS");
INSERT INTO PALABRAS VALUES(52,"ESGRIMA","DEPORTE","TRAJE BLANCO");
INSERT INTO PALABRAS VALUES(53,"GOLF","DEPORTE","BUSOS RECUPERAN PELOTAS");
INSERT INTO PALABRAS VALUES(54,"ESPORT","DEPORTE","DIGITAL");
INSERT INTO PALABRAS VALUES(55,"JIRAFA","ANIMALES","ALTA");
INSERT INTO PALABRAS VALUES(56,"CEBRA","ANIMAL","LADRA");
INSERT INTO PALABRAS VALUES(57,"BELUGA","ANIMAL","PUEDE CAMBIAR LA FORMA DE SU MELON");
INSERT INTO PALABRAS VALUES(58,"LEON","ANIMAL","REY");
INSERT INTO PALABRAS VALUES(59,"ABEJA","ANIMAL","NO NEGOCIAN CON TERRORISTAS");
INSERT INTO PALABRAS VALUES(60,"HORMIGAS","ANIMAL","HAY MAS QUE HUMANOS");
INSERT INTO PALABRAS VALUES(61,"GANSO","ANIMAL","EL DIOS DE ESTE JUEGO");
INSERT INTO PALABRAS VALUES(62,"AXOLOTE","ANIMAL","NATIVO DE MEXICO");
INSERT INTO PALABRAS VALUES(63,"BALLENA","ANIMAL","MAS GRANDE DEL MUNDO");
INSERT INTO PALABRAS VALUES(64,"TARANTULA","ANIMAL","MUDA DE PIEL");
INSERT INTO PALABRAS VALUES(65,"CUCARACHA","ANIMAL","VUELA=? CORRE");
INSERT INTO PALABRAS VALUES(66,"CABALLO","ANIMAL","JUAN XD");
INSERT INTO PALABRAS VALUES(67,"MERCURIO","PLANETAS","METAL");
INSERT INTO PALABRAS VALUES(68,"VENUS","PLANETAS","EL AMS CALIENTE");
INSERT INTO PALABRAS VALUES(69,"TIERRA","PLANETAS","TIENE SATELITES");
INSERT INTO PALABRAS VALUES(70,"MARTE","PLANETAS","SEGUNDO MAS PEQUEÑO");
INSERT INTO PALABRAS VALUES(71,"JUPITER","PLANETAS","BRILLA");
INSERT INTO PALABRAS VALUES(72,"SATURNO","PLANETAS","SEGUNDO MAS GRANDE");
INSERT INTO PALABRAS VALUES(73,"URANO","PLANETAS","PADRE DE CRONO");
INSERT INTO PALABRAS VALUES(74,"NEPTUNO","PLANETAS","GIGANTE HELADO");
INSERT INTO PALABRAS VALUES(75,"TWITCH","PAGINA","STREAMS");
INSERT INTO PALABRAS VALUES(76,"PUERTA","OBJETO","ENTRAR/SALIR");
INSERT INTO PALABRAS VALUES(77,"PRINCIPITO","LIBROS","LOBO Y ROSA");
INSERT INTO PALABRAS VALUES(78,"DICCIONARIO","LIBROS","TIENLE PALABRAS XD");
INSERT INTO PALABRAS VALUES(79,"MEDICO","PROFESIONES","USA BATA");
INSERT INTO PALABRAS VALUES(80,"CARPINTERO","PROFESIONES","USA MADERA");
INSERT INTO PALABRAS VALUES(81,"ELECTRICISTA","PROFESIONES","USA CABLES");
INSERT INTO PALABRAS VALUES(82,"CARNCIERO","PROFESIONES","USA CUCHILLOS");
INSERT INTO PALABRAS VALUES(83,"FLORISTA","PROFESIONES","HACE ARREGLOS");
INSERT INTO PALABRAS VALUES(84,"COMERCIENTE","PROFESIONES","COMPRA Y VENDE");
INSERT INTO PALABRAS VALUES(85,"ARQUITECTO","PROFESIONES","PLANOS");
INSERT INTO PALABRAS VALUES(86,"POLICIA","PROFESIONES","LA LEY");
INSERT INTO PALABRAS VALUES(87,"CAZADOR","PROFESIONES","USA ARMAS");
INSERT INTO PALABRAS VALUES(88,"MAESTRO","PROFESIONES","USA LIBROS");
INSERT INTO PALABRAS VALUES(89,"CATARATAS","LUGARES","CAIDA DE AGUA");
INSERT INTO PALABRAS VALUES(90,"FANTASMAS","MOUNSTRUO","TRANSPARENTE");
INSERT INTO PALABRAS VALUES(91,"MURALLA","LUGARES","PARA PROTEGER");
INSERT INTO PALABRAS VALUES(92,"HAWAII","LUGARES","TIENE VOLCAN");
INSERT INTO PALABRAS VALUES(93,"PIRAMIDE","LUGAR","4 LADOS TRIANGULARES");
INSERT INTO PALABRAS VALUES(94,"NIEVE","OBJETO","ES BLANCA");
INSERT INTO PALABRAS VALUES(95,"ALIEN","CRIATURAS","HOJON");
INSERT INTO PALABRAS VALUES(96,"SASQUATCH","CRIATURAS","LLENO DE PELO");
INSERT INTO PALABRAS VALUES(97,"SLENDERMAN","CRIATURAS","USA TRAJES");
INSERT INTO PALABRAS VALUES(98,"CHUPACABRAS","CRIATURAS","TOMA SANGRE");
INSERT INTO PALABRAS VALUES(99,"MELODIA","SONIDO","ARMONIA MUSICAL");
INSERT INTO PALABRAS VALUES(100,"TEQUILA","BEBIDA","ALCOHOL");

